# Generated by Django 6.0.2 on 2026-03-22 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('urgent', 'Urgent'), ('event', 'Event'), ('finance', 'Finance'), ('general', 'General')], default='general', max_length=20)),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('students', 'Students Only'), ('parents', 'Parents Only'), ('teachers', 'Teachers Only')], default='everyone', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_urgent', '-created_at'],
            },
        ),
    ]
